# Generated by Django 6.0.7 on 2026-07-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='location',
        ),
        migrations.AddField(
            model_name='camera',
            name='last_OK',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='last_check',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='metka',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='camera',
            name='ping',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='camera',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='camera',
            name='model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='camera',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
