# Generated by Django 5.2.4 on 2026-07-08 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0002_remove_camera_location_camera_last_ok_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='last_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
