# Generated by Django 5.2.4 on 2026-07-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_alter_camera_id_alter_camera_last_check'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='telegram_photos/%Y/%m/%d/')),
                ('telegram_id', models.BigIntegerField(db_index=True)),
                ('telegram_username', models.CharField(blank=True, max_length=100)),
                ('telegram_first_name', models.CharField(blank=True, max_length=100)),
                ('caption', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
